name: Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint source code
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          repository: garethr/snykum
          add_git_labels: true
          tag_with_sha: true
          tag_with_ref: true
          push: false
          args: --platform=linux/arm64 --load
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: garethr/snykum
          args: --file=Dockerfile --platform=linux/arm64 --project-name=docker.io/garethr/snykum
      - name: Login
        uses: docker://docker/github-actions:v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          args: login
      - name: Push image to Docker Hub
        uses: docker://docker/github-actions:v1
        with:
          repository: garethr/snykum
          tag_with_sha: true
          tag_with_ref: true
          args: push
