name: Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - name: Build
        run: |
          docker build --platform=linux/arm64 --load -t garethr/snykum .
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: garethr/snykum
          args: --file=Dockerfile --platform=linux/arm64
      - name: Push image to Docker Hub
        container: docker/github-actions
        run: push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: garethr/snykum
          add_git_labels: true
          tag_with_sha: true
