name: Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - uses: docker/setup-buildx-action@master
      - name: Build image
        run: |
          docker buildx build --platform=linux/arm64 --load -t temporary .
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: temporary
          args: --file=Dockerfile --platform=linux/arm64 --project-name=docker.io/garethr/snykum
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image to Docker Hub
        run: |
          docker buildx build --platform=linux/arm64 --push -t garethr/snykum .
