name: Manifest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: Build manifest
        run: |
          docker manifest create garethr/snykum:multiarch --amend amd64/alpine:latest --amend arm64v8/debian:stable
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push manifest to Docker Hub
        run: |
          docker manifest push -p garethr/snykum:multiarch
