# Before platform is supported this should pass, as it's testing an alpine
# image without any vulnerabilities. Once platform is supported this should fail
# as it should test the debian image for ARM instead.

name: Multi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - name: Enable Docker daemon experimental mode
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - name: Run Snyk to check platform image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: garethr/snykum:multiarch
          args: --platform=linux/arm64 --experimental
